# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0002_auto_20170909_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип статуса заявки')),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_organization.Proposal'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_organization.Status_bid', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='credit_organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
        migrations.AlterField(
            model_name='form',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='credit_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_organization.Credit_organization'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
