# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0006_bid_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_bid',
        ),
    ]
