# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0009_auto_20170912_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_of_dispatch',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
