# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0012_auto_20170912_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_partners.Form', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_organization.Proposal', verbose_name='Предложение'),
        ),
    ]
