# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0013_auto_20170913_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='credit_organization',
            options={'verbose_name': 'Кредитная организация', 'verbose_name_plural': 'Кредитные организации'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
