# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0014_auto_20170913_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='credit_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Кредитная организация'),
        ),
        migrations.DeleteModel(
            name='Credit_organization',
        ),
    ]
