# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0015_auto_20170913_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Кредитная организация',
                'verbose_name_plural': 'Кредитные организации',
            },
        ),
        migrations.AlterField(
            model_name='proposal',
            name='credit_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_organization.Credit_organization', verbose_name='Кредитная организация'),
        ),
    ]
