# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_organization', '0016_auto_20170913_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'permissions': (('view_model', 'Can see bid'),), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
