# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата и время создания')),
                ('date_of_dispatch', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата и время создания')),
                ('date_of_change', models.DateTimeField(verbose_name='Дата и время изменения')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('dob', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=100, verbose_name='Паспорт')),
                ('scoring_ball', models.IntegerField(max_length=3, verbose_name='Скоринговый балл')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата и время создания')),
                ('date_of_change', models.DateTimeField(verbose_name='Дата и время изменения')),
                ('start_date_of_rotation', models.DateTimeField(verbose_name='Дата и время начала ротации')),
                ('end_date_of_rotation', models.DateTimeField(verbose_name='Дата и время окончания ротации')),
                ('name', models.CharField(max_length=250, verbose_name='Название предложения')),
                ('type_of_a_proposal', models.CharField(max_length=100, verbose_name='Тип')),
                ('min_scoring_ball', models.IntegerField(max_length=3, verbose_name='Минимальный скоринговый балл')),
                ('max_scoring_ball', models.IntegerField(max_length=3, verbose_name='Максимальный скоринговый балл')),
                ('credit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Credit_organization')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Form'),
        ),
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Proposal'),
        ),
    ]
