# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='scoring_ball',
            field=models.IntegerField(verbose_name='Скоринговый балл'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='max_scoring_ball',
            field=models.IntegerField(verbose_name='Максимальный скоринговый балл'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='min_scoring_ball',
            field=models.IntegerField(verbose_name='Минимальный скоринговый балл'),
        ),
    ]
