# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='phone_confirmation',
            field=models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], default='Нет', max_length=5, verbose_name='Телефон подтвержден'),
        ),
        migrations.AlterField(
            model_name='form',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='Ф.И.О'),
        ),
    ]
