# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partners', '0002_auto_20170911_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='full_name',
        ),
        migrations.AddField(
            model_name='form',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='form',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name='Фамилия'),
        ),
    ]
