# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partners', '0003_auto_20170912_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(default='', max_length=200, verbose_name='Фамилия'),
        ),
    ]
