# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partners', '0005_auto_20170912_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='scoring_ball',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скоринговый балл'),
        ),
    ]
