# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_partners', '0007_auto_20170913_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Анкета клиента', 'verbose_name_plural': 'Анкеты клиента'},
        ),
    ]
